import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.


# add all lib files
src = 	Glob('STM32L1xx_HAL_Driver/Src/*.c')	
src += ['CMSIS/Device/ST/STM32L1xx/Source/Templates/system_stm32l1xx.c']



path = [cwd + '/STM32L1xx_HAL_Driver/Inc',
    cwd + '/CMSIS/Device/ST/stm32l1xx/Include',
    cwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('STM32_HAL', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
