/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
***********************************************************************/

#include "DIALOG.h"
#include "GUI.h"
//#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include "app_scr_class8.h"
#include <stdio.h>
//#include "ssz_common.h"
//#include "widget_text.h"
//#include "widget_image.h"


/*********************************************************************
*
*       Defines
*
***********************************************************************/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)

#define MessageID	(GUI_ID_USER + 0x01)


/*********************************************************************
*
*       Static data
*
***********************************************************************/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  {WINDOW_CreateIndirect, "app_scr_class8", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0},
  
};
static int g_home_left_time;
/*********************************************************************
*
*       Static code
*
***********************************************************************/

static void put_message(double rate , double volume ,  double KVO_rate,uint8_t unit)
{
	char *p;
        const char *ptr;
        WM_HWIN hWin;
        
        hWin = WM_GetDialogItem(ui_get_current_hwin(), MessageID);
		if(unit == 0)
		{
			ptr = get_string(kStrBKGDUI_mL);
		}
		else if(unit == 1)
		{
			ptr = get_string(kStrBKGDUI_mg);
		}
		else if(unit == 2)
		{
			ptr = get_string(kStrBKGDUI_mcg);
		}
		else   //默认为mL
			{
			ptr = get_string(kStrBKGDUI_mL);
			}
		
        p = get_dynamic_string(kStrDynamic3);
        sprintf(p, ptr, rate,volume,KVO_rate);
      
        TEXT_SetText(hWin, p);     
}

static void _cbDialog(WM_MESSAGE * pMsg)
{
	GUI_RECT rect;
	WM_HWIN hWin;
	int len;
	const char *ptr;
        char *p;
        uint8_t strlen;
        
	switch (pMsg->MsgId) 
	{
		case WM_CREATE:
			
			break;
			
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);

			GUI_SetFont(get_font(14));
			//ptr = get_string(kStrBKGDUI);
                        //p = get_dynamic_string(kStrDynamic3);
			//strlen = sprintf(p, ptr, 10000.1,223,486);
                        
                        
			hWin = TEXT_CreateEx(0, 7, 255, 40, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER, MessageID, 0);
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin,GUI_BLACK );
			TEXT_SetTextColor(hWin, GUI_WHITE);
			WM_BringToTop(hWin);

			break;
	
		case WM_PAINT:
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(get_font(14));
				
			ptr = get_string(kStrReturn);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, 2, 46, strlen, 12);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_VCENTER);

			ptr = get_string(kStrstartedit);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, 198, 46, strlen, 16);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_VCENTER);
			
			break; 
		
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}
}

/*********************************************************************
*
*       Public code
*
***********************************************************************/
WM_HWIN app_scr_class8_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	
	return hWin;
}


int app_scr_class8_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{
	//g_home_left_time = msg->SItem.DataValArray[4];
	//put_infusion_state(msg->SItem.DataValArray[5]);
	//put_infusion_dose(msg->SItem.DataValArray[6], msg->SItem.DataValArray[7]);
	//put_infusion_seed(msg->SItem.DataValArray[8]);

	double rate ;
	double volume ;
	double KVO_rate;

	rate = 	msg->SItem.DataValArray[1]*1000 	+
			msg->SItem.DataValArray[2]*100 		+
			msg->SItem.DataValArray[3]*10 		+
			msg->SItem.DataValArray[4]			+
			msg->SItem.DataValArray[5]*0.1		;

	volume= msg->SItem.DataValArray[6]*1000 	+
			msg->SItem.DataValArray[7]*100 		+
			msg->SItem.DataValArray[8]*10 		+
			msg->SItem.DataValArray[9]			+
			msg->SItem.DataValArray[10]*0.1		;

	KVO_rate= msg->SItem.DataValArray[11]*1000 	+
			msg->SItem.DataValArray[12]*100 	+
			msg->SItem.DataValArray[13]*10		+
			msg->SItem.DataValArray[14]			+
			msg->SItem.DataValArray[15]*0.1		;

	put_message(rate,volume,KVO_rate,msg->SItem.DataValArray[16]);
	
 	return 0;	
}

void app_scr_class8_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}

/*************************** End of file ****************************/

