/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/



#include "DIALOG.h"
#include "GUI.h"
//#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include "app_scr_class19.h"
#include <stdio.h>


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0         (GUI_ID_USER + 0x00)
#define MessageID1				(GUI_ID_USER + 0x01)	
#define MessageID2				(GUI_ID_USER + 0x02)
#define MessageID3			(GUI_ID_USER + 0x03)
#define MessageID4			(GUI_ID_USER + 0x04)
#define SELECT_IMAGE_ID			(GUI_ID_USER + 0x05)


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_scr_class19", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


static void move_cursor(uint8_t index)
{
	WM_HWIN hWin;
	uint8_t strlen, img_len, dlen, x;


	GUI_SetFont(get_font(60));
	strlen = GUI_GetStringDistX("00");
	img_len = GUI_GetStringDistX(":");
	dlen = 16+ 2*strlen + img_len;
	x = (DISPLAY_WIDTH - dlen)/2;
	hWin = WM_GetDialogItem(ui_get_current_hwin(), SELECT_IMAGE_ID);
	if(0 == index)
	{
		WM_MoveChildTo(hWin, x, 32);
	}
	else if(1 == index)
	{
		WM_MoveChildTo(hWin, x+8+strlen+img_len, 32);
	}
}


static void push_message(uint8_t UIID,uint8_t Forword,uint8_t backword,uint8_t seriesID ,uint8_t seriesIDall)
{
	const GUI_BITMAP *bitmap;
	WM_HWIN hWin;
	char p[50];
	const char * ptr;
	
    hWin = WM_GetDialogItem(ui_get_current_hwin(), MessageID2);
	sprintf(p, "%d/%d", seriesID,seriesIDall);	
	TEXT_SetText(hWin, p);	

	
	switch(UIID)
	{
		case 0:
			ptr = get_string(kStrSetHour);
			sprintf(p,"%02d : %02d",Forword,backword);
			
			break;
		case 1:
			ptr = get_string(kStrSetMonth);
			sprintf(p,"%02d - %02d",Forword,backword);
			
			break;
		case 2:
			ptr = get_string(kStrSetYear);
			sprintf(p,"%02d%02d",Forword,backword);
			
			break;
		default:

			break;
	}

	TEXT_SetText(WM_GetDialogItem(g_ui_common_param.win_id, MessageID1), ptr);	
	TEXT_SetText(WM_GetDialogItem(g_ui_common_param.win_id, MessageID3), p);	
	
	//move_cursor(cursorIndex);		
	return ;
}


static void _cbDialog(WM_MESSAGE * pMsg) 
{
	uint8_t strlen, img_len, dlen, x;
	GUI_RECT rect; 
	const char *ptr;
	WM_HWIN hWin;
	const GUI_BITMAP *bitmap;
	
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);

		                                             
			hWin = TEXT_CreateEx(1, 0, 100, 14, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_LEFT, MessageID1, 0);
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin,GUI_BLACK );
			TEXT_SetTextColor(hWin, GUI_WHITE);
			WM_BringToTop(hWin);

			strlen = GUI_GetStringDistX("1/3 ");                                               
			hWin = TEXT_CreateEx(220, 6, strlen, 14, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER, MessageID2, 0);
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin,GUI_BLACK );
			TEXT_SetTextColor(hWin, GUI_WHITE);
			WM_BringToTop(hWin);
			
			strlen = GUI_GetStringDistX("12: 45");                                               
			hWin = TEXT_CreateEx(50, 14, 150, 52, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER, MessageID3, 0);
			TEXT_SetFont(hWin, get_font(60));
			TEXT_SetBkColor(hWin,GUI_BLACK );
			TEXT_SetTextColor(hWin, GUI_WHITE);
			WM_BringToTop(hWin);

			//select
			bitmap = get_image(kImgSetArrow);
			hWin = IMAGE_CreateEx(85, 108, 16, 16, pMsg->hWin, 
				                  WM_CF_SHOW,  IMAGE_CF_AUTOSIZE, SELECT_IMAGE_ID);
			IMAGE_SetBitmap(hWin, bitmap);

			
			break;
	
		case WM_PAINT:
			GUI_SetColor(GUI_WHITE);

			GUI_SetFont(get_font(14));
				
			ptr = get_string(kStrReturn);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, 0, DISPLAY_HEIGHT-16, strlen, 16);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_VCENTER);

			ptr = get_string(kStrConfirm);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, DISPLAY_WIDTH-strlen, DISPLAY_HEIGHT-16, strlen, 16);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_RIGHT|GUI_TA_VCENTER);

			break; 
			
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}

}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/


WM_HWIN app_scr_class19_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}


int app_scr_class19_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{

	push_message(msg->SItem.DataValArray[4],
                    msg->ditem.DataValArray[1],
                    msg->ditem.DataValArray[2],
                    msg->SItem.DataValArray[2],
                    msg->SItem.DataValArray[3]);
	
 	return 0;	
}

void app_scr_class19_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}

/*************************** End of file ****************************/
