/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************/


#include "DIALOG.h"
#include "GUI.h"
//#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include "app_scr_class5.h"
#include <stdio.h>
//#include "ssz_common.h"
#include "rtthread.h"
#include "display.h"
#include "app_route.h"
/*********************************************************************
*
*       Defines
*
***********************************************************************/
#define ID_WINDOW_0     	(GUI_ID_USER + 0x00)

#define UNLOCK_ID_STR_1     (GUI_ID_USER + 0x01)
#define UNLOCK_ID_STR_2     (GUI_ID_USER + 0x02)
#define UNLOCK_ID_STR_3     (GUI_ID_USER + 0x03)
#define UNLOCK_ID_IMG	    (GUI_ID_USER + 0x04)
#define TITLE_ID 			(GUI_ID_USER + 0x05)

#define IMG_SET_ARROW_WIDTH		(8)	
#define IMG_SET_ARROE_HEIGH     (16)

/*********************************************************************
*
*       Static data
*
***********************************************************************/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, " app_scr_unlock_password_12100", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },

};

void get_one_image_and_char_coordinate(uint8_t cursor_index, GUI_RECT *rect)
{
	uint8_t data_width, sum_len;
	uint8_t one_image_and_data_with;
	uint8_t image_start_x, y;
	GUI_RECT rt;

	ssz_assert(cursor_index < 4);
	GUI_SetFont(get_font(60));
	data_width = GUI_GetStringDistX("1");
	
	one_image_and_data_with = data_width + IMG_SET_ARROW_WIDTH;
	sum_len = one_image_and_data_with*3 + IMG_SET_ARROW_WIDTH*2;

	image_start_x = (DISPLAY_WIDTH - sum_len)/2 + cursor_index*(one_image_and_data_with + IMG_SET_ARROW_WIDTH);
	y = 12;

	ui_rect_init_by_size(rt, image_start_x, y, one_image_and_data_with, DISPLAY_HEIGHT - 12);
	*rect = rt;
}


void get_image_coordinate(uint8_t cursor_index, GUI_RECT *rect)
{
	GUI_RECT rt, temp;

	get_one_image_and_char_coordinate(cursor_index, &rt);
	
	ui_rect_init_by_size(temp, rt.x0, rt.y0, IMG_SET_ARROW_WIDTH, DISPLAY_HEIGHT - 12);	

	*rect = temp;
}


void get_char_coordinate(uint8_t cursor_index, GUI_RECT *rect)
{
	GUI_RECT rt, temp;
	get_one_image_and_char_coordinate(cursor_index, &rt);

	ui_rect_init_by_size(temp, rt.x0 + IMG_SET_ARROW_WIDTH, rt.y0, 
		                 (rt.x1-rt.x0 + 1) - IMG_SET_ARROW_WIDTH, DISPLAY_HEIGHT - 12);	
	*rect = temp;
}


void put_select_arrow(uint8_t cursor_index)
{
	GUI_RECT rect;
	get_image_coordinate(cursor_index, &rect);
	WM_MoveChildTo(WM_GetDialogItem(ui_get_current_hwin(), UNLOCK_ID_IMG), rect.x0, 
		           rect.y0 + ((rect.y1 - rect.y0 +1) - IMG_SET_ARROE_HEIGH)/2+3);
}

static void put_select_password(uint8_t cursor_index, uint8_t data)
{
	GUI_RECT rect;
	char *p;
	int id[3] = {UNLOCK_ID_STR_1, UNLOCK_ID_STR_2, UNLOCK_ID_STR_3};
	get_char_coordinate(cursor_index, &rect);
	p = get_dynamic_string(kStrDynamic1);
	sprintf(p, "%d", data); 
	TEXT_SetText(WM_GetDialogItem(ui_get_current_hwin(), id[cursor_index]), p);
}

static void put_title(uint8_t title_index)
{
	WM_HWIN hWin;
	const char * ptr;
	hWin = WM_GetDialogItem(ui_get_current_hwin(),TITLE_ID);

	if(title_index == 0)
	{
		ptr = get_string(kStrInputPasswordToUnlock);
		TEXT_SetText(hWin,ptr);
	}
	else if(title_index == 1)
	{
		ptr = get_string(kStrSetPassword);
		TEXT_SetText(hWin,ptr);
	}
	
	
}

/*********************************************************************
*
*       Static code
*
***********************************************************************/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
	uint8_t strlen;
	GUI_RECT rect; 
	const char *ptr;
	WM_HWIN hWin;
	int i, id[3] = {UNLOCK_ID_STR_1, UNLOCK_ID_STR_2, UNLOCK_ID_STR_3};
	
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);

			//ptr = get_string(kStrInputPasswordToUnlock);
			//strlen = GUI_GetStringDistX(ptr);
			hWin = TEXT_CreateEx(2, 2, 100, 14, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_LEFT,  TITLE_ID, get_string(kStrInputPasswordToUnlock));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);
			
			for(i=0; i<3; i++)
			{//str
				get_char_coordinate(i, &rect);
				hWin = TEXT_CreateAsChild(rect.x0, rect.y0+5, rect.x1 - rect.x0 + 1, rect.y1 - rect.y0 + 1, pMsg->hWin, id[i], 
					                      WM_CF_SHOW, "0", GUI_TA_VCENTER|GUI_TA_HCENTER);
				TEXT_SetFont(hWin, get_font(60));
				TEXT_SetBkColor(hWin, GUI_BLACK);
				TEXT_SetTextColor(hWin, GUI_WHITE);
			}
			

			//img
			get_image_coordinate(0, &rect);
			hWin = IMAGE_CreateEx(rect.x0, rect.y0, rect.x1 - rect.x0 + 1, (rect.y1 - rect.y0 + 1)/2, pMsg->hWin, 
				                  WM_CF_SHOW,  IMAGE_CF_AUTOSIZE, UNLOCK_ID_IMG);
			IMAGE_SetBitmap(hWin, get_image(kImgSetArrow));

			break;
	
		case WM_PAINT:
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(get_font(14));
				
			ptr = get_string(kStrReturn);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, 0, DISPLAY_HEIGHT-16, strlen, 16);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_LEFT|GUI_TA_VCENTER);

	
			ptr = get_string(kStrConfirm);
			strlen = GUI_GetStringDistX(ptr);
			ui_rect_init_by_size(rect, DISPLAY_WIDTH-strlen, DISPLAY_HEIGHT-16, strlen, 16);
			GUI_DispStringInRect(ptr, &rect, GUI_TA_RIGHT|GUI_TA_VCENTER);
			break; 
			
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}

}

/*********************************************************************
*
*       Public code
*
***********************************************************************/
WM_HWIN app_scr_class5_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	//ui_clear_init_once_flag();
	return hWin;
}

int app_scr_class5_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{
	put_title(msg->SItem.DataValArray[1]);
	put_select_password(0,msg->ditem.DataValArray[1]);
	put_select_password(1,msg->ditem.DataValArray[2]);
	put_select_password(2,msg->ditem.DataValArray[3]);
	put_select_arrow(msg->CursorIndex.CursorIndex);

 	return 0;	
}

void app_scr_class5_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}


/*************************** End of file ****************************/
