/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "DIALOG.h"
#include "GUI.h"
//#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include "app_scr_class4.h"
#include <stdio.h>
//#include "ssz_common.h"
//#include "widget_text.h"
//#include "widget_image.h"
#include "string.h"
#include "rtdef.h"
#include "app_route.h"
#include "display.h"

/*********************************************************************
*
*       Defines
*
***********************************************************************/
#define ID_WINDOW_0     		  (GUI_ID_USER + 0x00)
#define ALARM_ID_STR_TYPE	      (GUI_ID_USER + 0x01)		
#define ALARM_ID_IMG_ALARM	      (GUI_ID_USER + 0x02)	
#define ALARM_ID_STR_ALARM	      (GUI_ID_USER + 0x03)
#define ALARM_ID_STR_LEFT_BOTTOM  (GUI_ID_USER + 0x04)	
#define ALARM_ID_STR_RIGHT_BOTTOM (GUI_ID_USER + 0x05)


#define IMG_ALARM_WIDTH			  (36)
#define IMG_ALARM_HEIGHT		  (36)
#define IMG_ALARM_START_X		  (16)

//alarm type
#define ALAMR_TYPE_NOTICE		  (0)
#define ALAMR_TYPE_CAUTION		  (1)
#define ALAMR_TYPE_WARNING		  (2)
#define ALAMR_TYPE_ERROR		  (3)



/*********************************************************************
*
*       Static data
*
***********************************************************************/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_scr_alarm_21000", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
***********************************************************************/
static const char *get_alarm_string(uint8_t alarm_code)
{

	switch(alarm_code)
	{
		case 2: return get_string(kStrInfusionWillBeFinishedInOneHour);
	
		default:
			break;
	}

	return NULL;
}

static void  put_alarm(uint8_t alarm_type, uint8_t alarm_code)
{
	WM_HWIN  hWin;
	char *p;
        const char *ptr;
	switch(alarm_type)
	{
		case ALAMR_TYPE_NOTICE:
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_TYPE);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrNotice));
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_ALARM);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_alarm_string(alarm_code));
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_LEFT_BOTTOM);
			WM_HideWindow(hWin);
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_RIGHT_BOTTOM);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrOk));	
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_IMG_ALARM);
			WM_HideWindow(hWin);	
			break;

		case ALAMR_TYPE_CAUTION:
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_TYPE);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrCaution));
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_ALARM);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrLowBattery));
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_LEFT_BOTTOM);
			WM_HideWindow(hWin);
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_RIGHT_BOTTOM);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrConfirm));	
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_IMG_ALARM);
			WM_HideWindow(hWin);	
			break;
			
		case ALAMR_TYPE_WARNING:
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_TYPE);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrWarning));
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_ALARM);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrTubeBlocked));
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_LEFT_BOTTOM);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrCloseAlarming));
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_RIGHT_BOTTOM);
			WM_ShowWindow(hWin);
			TEXT_SetText(hWin, get_string(kStrConfirm));	
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_IMG_ALARM);
			WM_ShowWindow(hWin);
			IMAGE_SetBitmap(hWin, get_image(kImgWarning));
			break;
			
		case ALAMR_TYPE_ERROR:
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_TYPE);
			WM_HideWindow(hWin);
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_ALARM);
			WM_ShowWindow(hWin);
			p = get_dynamic_string(kStrDynamic1);
			//strcpy(p, get_string(kStrSystemError));
			sprintf(p,"%s","Error code: ");
			sprintf(p + strlen(p), "%03d", alarm_code);
			TEXT_SetText(hWin, p);
			
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_LEFT_BOTTOM);
			//WM_HideWindow(hWin);
			ptr = get_string(kStrCloseAlarming);
			TEXT_SetText(hWin, ptr);
			
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_STR_RIGHT_BOTTOM);
			//WM_HideWindow(hWin);	
			ptr = get_string(kStrStopAlarming);
			TEXT_SetText(hWin, ptr);
			
			hWin = WM_GetDialogItem(ui_get_current_hwin(), ALARM_ID_IMG_ALARM);
			WM_ShowWindow(hWin);
			IMAGE_SetBitmap(hWin, get_image(kImgWarningCommon));
			break;

		default:
			break;
	}
}

static void _cbDialog(WM_MESSAGE * pMsg)
{
	WM_HWIN hWin;
	
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);
			//alarm type
			hWin = TEXT_CreateEx(0, 0, DISPLAY_WIDTH, 12, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER,  ALARM_ID_STR_TYPE, get_string(kStrWarning));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_WHITE);
			TEXT_SetTextColor(hWin, GUI_BLACK);
			
			//alarm string
			hWin = TEXT_CreateEx(IMG_ALARM_WIDTH+IMG_ALARM_START_X, (DISPLAY_HEIGHT -16)/2, DISPLAY_WIDTH - 2*(IMG_ALARM_WIDTH+IMG_ALARM_START_X), 16, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER,  ALARM_ID_STR_ALARM, get_string(kStrInfusionNearEmpty));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);

			//alarm image
			hWin = IMAGE_CreateEx(IMG_ALARM_START_X, 12, IMG_ALARM_WIDTH, IMG_ALARM_HEIGHT, pMsg->hWin, WM_CF_SHOW,  IMAGE_CF_AUTOSIZE, ALARM_ID_IMG_ALARM);
			IMAGE_SetBitmap(hWin, get_image(kImgWarning));

			//left bottom
			hWin = TEXT_CreateEx(0, DISPLAY_HEIGHT-16, DISPLAY_WIDTH/2, 16, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_LEFT,  ALARM_ID_STR_LEFT_BOTTOM, get_string(kStrCloseAlarming));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);

			//right bottom
			hWin = TEXT_CreateEx(DISPLAY_WIDTH/2, DISPLAY_HEIGHT-16, DISPLAY_WIDTH/2, 16, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_RIGHT,  ALARM_ID_STR_RIGHT_BOTTOM, get_string(kStrConfirm));
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin, GUI_BLACK);
			TEXT_SetTextColor(hWin, GUI_WHITE);
			break;
	
		case WM_PAINT:
			break; 
			
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}

}

/*********************************************************************
*
*       Public code
*
***********************************************************************/

WM_HWIN app_scr_class4_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	
	return hWin;
}


int app_scr_class4_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{

	put_alarm(ALAMR_TYPE_ERROR, msg->SItem.DataValArray[1]);

 	return 0;	
}

void app_scr_class4_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}


/*************************** End of file ****************************/
