/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "DIALOG.h"
#include "app_scr_class1.h"
#include "GUI.h"
//#include "ui_common.h"
#include "image_data.h"
#include "string_data.h"
#include "font_data.h"
#include <stdbool.h>
#include <stdint.h>
#include "display.h"
#include "app_route.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_LOGO                 (GUI_ID_USER + 0x01)
#define ID_STRING1    (GUI_ID_USER + 0x02)   //标题栏文字
#define ID_STRING2    (GUI_ID_USER + 0x03)   //正文内容

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "app_scr_class1", ID_WINDOW_0, 0, 0, 256, 64, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static void put_message(uint8_t id)
{
  WM_HWIN hWin;
  const char *ptr;
  GUI_CONST_STORAGE GUI_BITMAP* mapinfo;
 
  switch(id)
  {
  case 1:    //logo  
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING1);
      TEXT_SetText(hWin," ");
    
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING2);
      TEXT_SetText(hWin," ");
    
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_LOGO);
      mapinfo = get_image(kImgLogo);
      IMAGE_SetBitmap(hWin, mapinfo);
      WM_BringToTop(hWin);
    break;  
  case 2:  //密码更改生效
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING1);

      TEXT_SetText(hWin, "");
    
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING2);
      ptr = get_string(kStrChangePasswordOk);
      TEXT_SetText(hWin, ptr);
      WM_BringToTop(hWin);
    
    break;  
  case 3:  //解锁失败

    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING1);
      TEXT_SetText(hWin, " ");
    
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING2);
      ptr = get_string(kStrUnlockfail);
      TEXT_SetText(hWin, ptr);
      WM_BringToTop(hWin);
      break;
      
  case 4:  //开关机确认

    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING1);
      TEXT_SetText(hWin, " ");
    
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING2);
      ptr = get_string(kStrPowerOffOnCheck);
      TEXT_SetText(hWin, ptr);
      WM_BringToTop(hWin);
      break;   
      
  case 5:  //排气中

    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING1);
      ptr = get_string(kStrDoNotConnectBody);
      TEXT_SetText(hWin, ptr);
    
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING2);
      ptr = get_string(kStrInfusionStop);
      TEXT_SetText(hWin, ptr);
      WM_BringToTop(hWin);
      break;        
      
  case 6:  //排气暂停

    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING1);
      ptr = get_string(kStrDoNotConnectBody);
      TEXT_SetText(hWin, ptr);
    
    hWin = WM_GetDialogItem(ui_get_current_hwin(), ID_STRING2);
      ptr = get_string(kStrInfusionPause);
      TEXT_SetText(hWin, ptr);
      WM_BringToTop(hWin);
      break;       
      
      
      
      
  default:
    
    
    
    
    break;
  }
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
	WM_HWIN hItem;
        WM_HWIN hWin;
	int x, y;
        GUI_CONST_STORAGE GUI_BITMAP* mapinfo;
        const char *ptr;
        
	switch (pMsg->MsgId) 
	{
		case WM_INIT_DIALOG:
			WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);
                        			
			//logo
			mapinfo = get_image(kImgLogo);
			hWin = IMAGE_CreateEx((256 - mapinfo->XSize)/2, (64 - mapinfo->YSize)/2, mapinfo->XSize, mapinfo->YSize, pMsg->hWin, WM_CF_SHOW,  IMAGE_CF_AUTOSIZE, ID_LOGO);
			//IMAGE_SetBitmap(hWin, 0);
  
			ptr = get_string(kStrDoNotConnectBody);
			hWin = TEXT_CreateEx(9, 5, 150, 14, pMsg->hWin,WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER, ID_STRING1, 0);
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin,GUI_BLACK );
			TEXT_SetTextColor(hWin, GUI_WHITE);
			WM_BringToTop(hWin);
                        
						
			hWin = TEXT_CreateEx(0, 19, 256, 50, pMsg->hWin, 
				                 WM_CF_SHOW, GUI_TA_VCENTER|GUI_TA_HCENTER, ID_STRING2, 0);
			TEXT_SetFont(hWin, get_font(14));
			TEXT_SetBkColor(hWin,GUI_BLACK );
			TEXT_SetTextColor(hWin, GUI_WHITE);
			WM_BringToTop(hWin);
                        
			break;
	
		case WM_PAINT:

			break;  
		default:
			  WM_DefaultProc(pMsg);
			  break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

WM_HWIN app_scr_class1_create(type_MsgBody4UICtrlMsg *msg) 
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;

}


int app_scr_class1_update(WM_HWIN hwin, type_MsgBody4UICtrlMsg *msg)
{
//	//GUI_RECT rect = {24, 48, 104, 56}; 
//
//	switch(msg->OpMethod)
//	{
//		case SCR_CURSER_MOVE:
//			break;
//
//		case SCR_VALUE_ALTER:
//			//WM_SetUserData(hwin, (uint8_t *)&msg->DItem[0], 4);
//			//WM_InvalidateRect(hwin, &rect);
//			break;
//
//		default:
//			break;
//	}
      put_message(msg->SItem.DataValArray[1]);
      
      
 	return 0;	
}

void app_scr_class1_destroy(WM_HWIN win_id) 
{
	GUI_EndDialog(win_id, 0);
}

/*************************** End of file ****************************/

