from building import *

cwd     = GetCurrentDir()
src = Split('''
''')
CPPPATH = [cwd]

if GetDepend(['RT_USING_EMWIN']):
    src     = Glob('*.c')

group = DefineGroup('emWin', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
