from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
src     = src + Glob('font/*.c')
src     = src + Glob('image/*.c')
CPPPATH = [cwd]

group = DefineGroup('emWin', src, depend = [''], CPPPATH = CPPPATH)

Return('group')