/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: infusion_stop                                         *
* Dimensions:  16 * 16                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bminfusion_stop;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsinfusion_stop[] = {
#if (GUI_USE_ARGB == 0)
  0xFFFFFF, 0x000000
#else
  0xFFFFFFFF, 0xFF000000
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palinfusion_stop = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsinfusion_stop[0]
};

static GUI_CONST_STORAGE unsigned char _acinfusion_stop[] = {
  0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00,
  0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00,
  0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00,
  0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00,
  0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00,
  0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00,
  0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00,
  0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bminfusion_stop = {
  16, // xSize
  16, // ySize
  8, // BytesPerLine
  4, // BitsPerPixel
  _acinfusion_stop,  // Pointer to picture data (indices)
  &_Palinfusion_stop   // Pointer to palette
};

/*************************** End of file ****************************/
