/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mute_small                                            *
* Dimensions:  10 * 10                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmmute_small;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsmute_small[] = {
#if (GUI_USE_ARGB == 0)
  0xFFFFFF, 0x000000
#else
  0xFFFFFFFF, 0xFF000000
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palmute_small = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsmute_small[0]
};

static GUI_CONST_STORAGE unsigned char _acmute_small[] = {
  0x01, 0x11, 0x00, 0x11, 0x10,
  0x10, 0x10, 0x00, 0x01, 0x01,
  0x11, 0x00, 0x00, 0x00, 0x11,
  0x11, 0x01, 0x00, 0x10, 0x11,
  0x11, 0x00, 0x00, 0x00, 0x11,
  0x11, 0x00, 0x00, 0x00, 0x11,
  0x11, 0x01, 0x00, 0x10, 0x11,
  0x11, 0x00, 0x00, 0x00, 0x11,
  0x10, 0x00, 0x00, 0x00, 0x01,
  0x01, 0x11, 0x00, 0x11, 0x10
};

GUI_CONST_STORAGE GUI_BITMAP bmmute_small = {
  10, // xSize
  10, // ySize
  5, // BytesPerLine
  4, // BitsPerPixel
  _acmute_small,  // Pointer to picture data (indices)
  &_Palmute_small   // Pointer to palette
};

/*************************** End of file ****************************/
