/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: right_arrow                                           *
* Dimensions:  8 * 8                                                 *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmright_arrow;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsright_arrow[] = {
#if (GUI_USE_ARGB == 0)
  0xFFFFFF, 0x000000
#else
  0xFFFFFFFF, 0xFF000000
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palright_arrow = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsright_arrow[0]
};

static GUI_CONST_STORAGE unsigned char _acright_arrow[] = {
  0x01, 0x11, 0x11, 0x11,
  0x00, 0x01, 0x11, 0x11,
  0x00, 0x00, 0x01, 0x11,
  0x00, 0x00, 0x00, 0x01,
  0x00, 0x00, 0x00, 0x01,
  0x00, 0x00, 0x01, 0x11,
  0x00, 0x01, 0x11, 0x11,
  0x01, 0x11, 0x11, 0x11
};

GUI_CONST_STORAGE GUI_BITMAP bmright_arrow = {
  8, // xSize
  8, // ySize
  4, // BytesPerLine
  4, // BitsPerPixel
  _acright_arrow,  // Pointer to picture data (indices)
  &_Palright_arrow   // Pointer to palette
};

/*************************** End of file ****************************/
